#!/usr/bin/env python

# this file has a symlink to the .git/hooks folder
# this way it can be entered into vcs while still being executable

import os
import subprocess

print "post commit hook style 2"


with open(".commit_id", "w") as f:
	f.write("iurwbgoubn")

print("post commit hook")