#!/usr/bin/python3

# this file has a symlink to the .git/hooks folder
# this way it can be entered into vcs while still being executable

import os
import subprocess


# remove old commit id if it exists
try:
	os.remove('.commit_id')
except OSError:
	pass

# make new file
with open('.commit_id', 'w') as f:
	# get the latest commit id
	commit = subprocess.check_output(['git', 'log', '-n1'])
	commit_id = commit.split()[1].decode('utf-8')
	f.write(commit_id)

# print the current working directory
print(os.getcwd())