#!/usr/bin/python3

# this file has a symlink to the .git/hooks folder of the test repo
# this way it can be entered into vcs while still being executable

import os
import subprocess

SERVER_AND_PORT = "localhost:8888"

commit = subprocess.check_output(['git', 'log', '-n1'])
commit_id = commit.split()[1].decode('utf-8')

print("Post commit hook is dispatching tests against commit: " + commit_id)

# change working directory to where the ci server scripts are
os.chdir('../..')



# call the repo_observer
# fill in the server name port and commit id
# e.g. python repo_observer.py --dispatcher-server=localhost:8888 --commit-id=17eb587b44f6480db31987602f703c7f7b8628cb
subprocess.call(["python", "repo_observer.py", f"--dispatcher-server={SERVER_AND_PORT}", f"--commit-id={commit_id}"])